Corrigido o arquivo de configuração do CI/CD azure-pipelines.yml para rodar no windows e testando variaveis de ambiente

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -53,6 +53,10 @@ stages:
                   displayName: 'Trigger Render Staging Deploy'
                   inputs:
                     script: |
+                      if "%RENDER_DEV_HOOK%"=="" (
+                      echo "ERROR: RENDER_DEV_HOOK is not set!"
+                          exit 1
+                      )
                       echo Triggering Render staging deploy...
                       curl -k -X POST "%RENDER_DEV_HOOK%"
   - stage: Deploy_Prod
@@ -73,5 +77,9 @@ stages:
                   displayName: 'Trigger Render Production Deploy'
                   inputs:
                     script: |
+                      if "%RENDER_PROD_HOOK%"=="" (
+                      echo "ERROR: RENDER_PROD_HOOK is not set!"
+                          exit 1
+                      )
                       echo Triggering Render production deploy...
                       curl -k -X POST "%RENDER_PROD_HOOK%"
